# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4eb994933c8aaca98fc5a864cb870941f644216de6686681950a66c464e5eba029e204d83ee1a2ca5282d53e5673a0f1ffd52dd6fe0b304ebdfbbc1c7f24902c

test:
  secret_key_base: 2209b07a90daf5a4d23332ac0b1bf1c7931f019d8469d6b64204649e2c29285084ae937d9fe983724ec3db8a111fb83c021ffb4a88481d4839e227ba43f92459

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
